[mgr]
hovered         = { fg = "#1a1b26", bg = "#7aa2f7" }
preview_hovered = { underline = true }

marker_copied   = { fg = "#9ece6a", bg = "#9ece6a" }
marker_cut      = { fg = "#f7768e", bg = "#f7768e" }
marker_marked   = { fg = "#7aa2f7", bg = "#7aa2f7" }
marker_selected = { fg = "#e0af68", bg = "#e0af68" }

tab_active   = { fg = "#1a1b26", bg = "#bb9af7" }
tab_inactive = { fg = "#a9b1d6", bg = "#292e42" }
tab_width_max = 20

tab_sep_inner = { open = "[", close = "]" }
tab_sep_outer = { open = "", close = "" }

count_copied   = { fg = "#1a1b26", bg = "#9ece6a" }
count_cut      = { fg = "#1a1b26", bg = "#f7768e" }
count_selected = { fg = "#1a1b26", bg = "#e0af68" }

border_symbol = "│"

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

separator_open  = ""
separator_close = ""

mode_normal_main = { fg = "#1a1b26", bg = "#7aa2f7" }
mode_normal_alt  = { fg = "#7aa2f7", bg = "#292e42" }
mode_select_main = { fg = "#1a1b26", bg = "#bb9af7" }
mode_select_alt  = { fg = "#bb9af7", bg = "#292e42" }
mode_unset_main  = { fg = "#1a1b26", bg = "#f7768e" }
mode_unset_alt   = { fg = "#f7768e", bg = "#292e42" }

progress_normal = { fg = "#7aa2f7", bg = "#292e42" }
progress_error  = { fg = "#f7768e", bg = "#292e42" }

[input]
selected = { reversed = true }

[tasks]
hovered = { underline = true }

[which]
mask      = { bg = "#16161e" }
separator = "  "

[help]
hovered = { bg = "#7aa2f7", fg = "#1a1b26", bold = true }

[confirm]
btn_yes = { reversed = true }

[indicator]
padding = { open = "█", close = "█" }
