#!/bin/sh

rfkill unblock all

export XDG_CURRENT_DESKTOP=wlroots
export XDG_SESSION_TYPE=wayland

exec dbus-run-session -- sh -c '
	pipewire &
	PW_PID=$!
	pipewire-pulse &
	PWPULSE_PID=$!
	wireplumber &
	WP_PID=$!

	pkill -9 -x xdg-desktop-portal-wlr 2>/dev/null
	pkill -9 -x xdg-desktop-portal 2>/dev/null

	CLIPSTART="wl-paste --type text --watch cliphist store & wl-paste --type image --watch cliphist store &"

	WALLPAPER="$(cat "$HOME/.cache/current_wallpaper" 2>/dev/null || echo "$HOME/Pictures/Wallpapers/default.jpg")"
	WALLSTART="swaybg -i \"$WALLPAPER\" -m fill &"

	PORTALSTART="/usr/lib/xdg-desktop-portal-wlr & sleep 1; /usr/lib/xdg-desktop-portal &"

	trap "kill \$PW_PID \$PWPULSE_PID \$WP_PID 2>/dev/null" EXIT

	slstatus -s | dwl -s "$CLIPSTART $WALLSTART $PORTALSTART"
'
